<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Vela Launcher</AssemblyName>
    <RootNamespace>VelaLauncher.Host</RootNamespace>
    <ApplicationIcon Condition="Exists('Assets\vela.ico')">Assets\vela.ico</ApplicationIcon>
    <Version>0.2.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="wwwroot\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\vela-client.jar" CopyToOutputDirectory="PreserveNewest" Condition="Exists('Assets\vela-client.jar')" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CmlLib.Core" Version="4.0.6" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.11" />
  </ItemGroup>
</Project>
